const HTTP_OK_STATUS = 200;
const HTTP_OK_CREATED = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_NOT_FOUND = 404;
const PORT = '3000';

module.exports = {
  HTTP_OK_STATUS,
  PORT,
  HTTP_NOT_FOUND,
  HTTP_BAD_REQUEST,
  HTTP_OK_CREATED,
  HTTP_UNAUTHORIZED,
};
